### ISSUE TITLE
dll call error

### ISSUE THREAD

**Issue by fenchai23** [kazhafeizhale/imgui4ahk#1]
hi, I was testing v1 example and it always gives me dll call errors_ImGui_Load, _ImGui_GuiCreate, _ImGui_GuiGetIO and many more, I am on windows 10 x64 with AHK v1.

**Comment by sxzxs** [comment]
you may need install d3d11 or other depend dll
![image](https://user-images.githubusercontent.com/26515268/167054688-cbc49a0b-defc-437d-aa9d-a6ae284f13a1.png)
you can use some dx Repair tools
