### ISSUE TITLE
增加操作图片相关的示例

### ISSUE THREAD

**Issue by Frozen1084** [kazhafeizhale/imgui4ahk#3]
我在显示图片方面，一直有两个问题。一是GDIP加载大尺寸或者大体积的图像非常缓慢，GDIP只能使用CPU的算力。二是支持的格式非常落后，从浏览器下载的各种新兴图片格式都无法操作。

这个库作为图片库使用来解决这两个问题吗？如果能，能否增加相关的示例？谢谢。

**Comment by sxzxs** [comment]
demo1,demo2,demo3都有图片加载的例子，opencv-demo有opencv读取imgui显示的例子

**Comment by Frozen1084** [comment]
谢谢。
我看到你在论坛发的帖子"简单搜索框"，它真的没有显示出这个库的优点来。
应该把opencv-demo显示gif的示例拿出来，论坛还没有一个显示gif的完美方案。
